CREATE TABLE travel_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL UNIQUE,
    user_account_id BIGINT NOT NULL,
    shared_preferences TEXT NOT NULL,
    budget_min DECIMAL(12,2) NOT NULL,
    budget_max DECIMAL(12,2) NOT NULL,
    destination_summary VARCHAR(512) NOT NULL,
    travel_start_date DATE NOT NULL,
    travel_end_date DATE NOT NULL,
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_flexible_date BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_travel_requests_trip
        FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_travel_requests_user_account
        FOREIGN KEY (user_account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_travel_requests_trip_id ON travel_requests (trip_id);
CREATE INDEX idx_travel_requests_user_account_id ON travel_requests (user_account_id);
