CREATE TABLE offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    agency_account_id BIGINT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    currency VARCHAR(64) NOT NULL,
    accommodation_details VARCHAR(512) NOT NULL,
    transport_details VARCHAR(512) NOT NULL,
    itinerary_summary TEXT,
    conditions TEXT,
    attachment_url VARCHAR(1024),
    feedback_message TEXT,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_offers_request
        FOREIGN KEY (request_id) REFERENCES travel_requests (id),
    CONSTRAINT fk_offers_agency_account
        FOREIGN KEY (agency_account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_offers_request_id ON offers (request_id);
CREATE INDEX idx_offers_agency_account_id ON offers (agency_account_id);
