CREATE TABLE trip_budget_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_budget_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    allocated_amount DECIMAL(12,2) NOT NULL,
    spent_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_trip_budget_categories_budget
        FOREIGN KEY (trip_budget_id) REFERENCES trip_budgets (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_trip_budget_categories_budget_category
        UNIQUE (trip_budget_id, category)
);

CREATE INDEX idx_trip_budget_categories_budget_id
    ON trip_budget_categories (trip_budget_id);
