CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(255)
);

INSERT INTO roles (name, description)
VALUES
    ('AGENCY', 'Travel agency account'),
    ('USER', 'Regular user account'),
    ('ADMIN', 'Administrator account');
