CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    first_name VARCHAR(155),
    last_name VARCHAR(155),
    phone VARCHAR(30) NOT NULL,
    profile_picture_url VARCHAR(500),
    city VARCHAR(50),
    country VARCHAR(50),
    agency_name VARCHAR(155),
    agency_description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_approved BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_profiles_account
        FOREIGN KEY (account_id) REFERENCES accounts (id)
);
