CREATE TABLE destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    city VARCHAR(125) NOT NULL,
    country VARCHAR(125) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_destinations_trip
        FOREIGN KEY (trip_id) REFERENCES trips (id)
);

CREATE INDEX idx_destinations_trip_id ON destinations (trip_id);
