CREATE TABLE activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    destination_id BIGINT,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    activity_date DATE NOT NULL,
    start_time TIME NOT NULL,
    duration_minutes INT NOT NULL,
    estimated_cost DECIMAL(12,2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activities_trip
        FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_activities_destination
        FOREIGN KEY (destination_id) REFERENCES destinations (id)
);

CREATE INDEX idx_activities_trip_id ON activities (trip_id);
CREATE INDEX idx_activities_destination_id ON activities (destination_id);
