CREATE TABLE ai_generated_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    prompt_data TEXT NOT NULL,
    generated_content TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_generated_drafts_account
        FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_ai_generated_drafts_account_id ON ai_generated_drafts (account_id);
